In [73]:
# Importing the libraries
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [74]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [75]:
df_train.head()

,id,title,Rating,maincateg,platform,price1,actprice1,Offer %,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
0,16695,Fashionable & Comfortable Bellies For Women (...,3.9,Women,Flipkart,698,999,30.13%,38.0,7.0,17.0,9.0,6.0,3,3,0
1,5120,Combo Pack of 4 Casual Shoes Sneakers For Men ...,3.8,Men,Flipkart,999,1999,50.03%,531.0,69.0,264.0,92.0,73.0,29,73,1
2,18391,Cilia Mode Leo Sneakers For Women (White),4.4,Women,Flipkart,2749,4999,45.01%,17.0,4.0,11.0,3.0,2.0,1,0,1
3,495,Men Black Sports Sandal,4.2,Men,Flipkart,518,724,15.85%,46413.0,6229.0,1045.0,12416.0,5352.0,701,4595,1
4,16408,Men Green Sports Sandal,3.9,Men,Flipkart,1379,2299,40.02%,77.0,3.0,35.0,21.0,7.0,7,7,1

In [76]:
df_train[df_train.maincateg.isna()]

,id,title,Rating,maincateg,platform,price1,actprice1,Offer %,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
19,12336,Women Beige Heels Sandal,4.0,NaN,Flipkart,499,999,50.05%,NaN,NaN,28.0,9.0,10.0,2,5,0
38,20804,"Men Brown, Orange Sports Sandal",4.1,NaN,Flipkart,819,999,18.02%,26640.0,3667.0,14148.0,NaN,NaN,1113,2094,1
68,5575,Women Copper Flats Sandal,4.1,NaN,Flipkart,349,999,65.07%,NaN,27.0,NaN,NaN,22.0,5,15,1
91,4262,Slippers,3.6,NaN,Flipkart,213,249,14.46%,NaN,NaN,NaN,NaN,466.0,281,476,1
116,2767,Ace Slip-On Running Shoes For Men (Black),4.3,NaN,Flipkart,2999,4999,40.01%,NaN,NaN,46.0,27.0,5.0,1,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15536,20013,Slides,4.5,NaN,Flipkart,499,799,37.55%,NaN,1.0,23.0,NaN,1.0,1,2,0
15570,9968,Women Multicolor Bellies Sandal,3.7,NaN,Flipkart,501,999,49.85%,NaN,NaN,NaN,141.0,111.0,75,128,1
15583,11224,Jutis For Men (Black),3.7,NaN,Flipkart,494,499,1.00%,NaN,NaN,22.0,NaN,4.0,4,8,0
15674,7209,Zod Runner V3 Wn s IDP Running Shoes For Women...,4.3,NaN,Flipkart,1699,3999,57.51%,NaN,NaN,NaN,NaN,268.0,102,140,1
15709,14826,Enzo Beta Wn's Basketball Shoes For Women (Br...,3.9,NaN,Flipkart,1701,5499,69.07%,NaN,NaN,NaN,NaN,6.0,2,10,1

In [77]:
df_test.head()

,id,title,Rating,maincateg,platform,actprice1,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
0,2242,Casuals For Men (Blue),3.8,Men,Flipkart,999,27928,3543,14238.0,4295,3457,1962,3976.0,1
1,20532,Women Black Flats Sandal,3.9,Women,Flipkart,499,3015,404,1458.0,657,397,182,321.0,1
2,10648,Women Gold Wedges Sandal,3.9,Women,Flipkart,999,449,52,229.0,70,71,33,46.0,1
3,20677,Men's Height Increasing High Heel Formal Party...,3.9,Men,Flipkart,2999,290,40,141.0,51,49,17,32.0,1
4,12593,Loafers For Men (Tan),3.9,Men,Flipkart,999,2423,326,1265.0,414,293,143,308.0,0

### Columns
* `title` - Name of the product
* `Rating` - average rating given to a product
* `maincateg` - category that the product is listed under(men/women)
* `platform` - platform on which it is sold on (Eg. Amazon, Flipkart)
* `price1` - Discounted Price of the listed product
* `actprice1` - Actual price of the listed product
* `Offer %` - Discount percent
* `norating1` - number of ratings available for a particular product
* `noreviews1` - number of reviews available for a particular product
* `star_5f` - number of five star ratings given to a particular product
* `star_4f` - number of four star ratings given to a particular product
* `star_3f` - number of three star ratings given to a particular product
* `star_2f` - number of two star ratings given to a particular product
* `star_1f` - number of one star ratings given to a particular product
* `fulfilled1` - whether it is Amazon fulfilled or not

### Keep in mind --- train data doesn't contain price1 and offer_% columns as the target is predicting the price of the comodity

In [78]:
print(df_train.shape)
print(df_test.shape)

(15730, 16)
(5244, 14)

In [79]:
df_test

,id,title,Rating,maincateg,platform,actprice1,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
0,2242,Casuals For Men (Blue),3.8,Men,Flipkart,999,27928,3543,14238.0,4295,3457,1962,3976.0,1
1,20532,Women Black Flats Sandal,3.9,Women,Flipkart,499,3015,404,1458.0,657,397,182,321.0,1
2,10648,Women Gold Wedges Sandal,3.9,Women,Flipkart,999,449,52,229.0,70,71,33,46.0,1
3,20677,Men's Height Increasing High Heel Formal Party...,3.9,Men,Flipkart,2999,290,40,141.0,51,49,17,32.0,1
4,12593,Loafers For Men (Tan),3.9,Men,Flipkart,999,2423,326,1265.0,414,293,143,308.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5239,14033,Women Off White Flats Sandal,NaN,Women,Flipkart,699,1235,153,NaN,323,155,62,NaN,1
5240,297,Slip On For Men (Tan),3.9,Men,Flipkart,1993,329,56,350.0,37,60,5,37.0,0
5241,18733,Women Grey Heels Sandal,3.8,Women,Flipkart,999,1280,135,574.0,290,172,94,150.0,0
5242,6162,Womens Casual Comfort Stylish Black High Heel ...,3.9,Women,Flipkart,499,4867,574,2384.0,974,648,328,533.0,0
5243,13574,ZAPATOZ Women's Casual PU Leather Sneaker Shoes,3.9,Women,Amazon,749,8,5,28.0,0,0,0,72.0,1

In [80]:
df_train.dtypes

id              int64
title          object
Rating        float64
maincateg      object
platform       object
price1          int64
actprice1       int64
Offer %        object
norating1     float64
noreviews1    float64
star_5f       float64
star_4f       float64
star_3f       float64
star_2f         int64
star_1f         int64
fulfilled1      int64
dtype: object

In [81]:
df_test.dtypes

id              int64
title          object
Rating        float64
maincateg      object
platform       object
actprice1       int64
norating1       int64
noreviews1      int64
star_5f       float64
star_4f         int64
star_3f         int64
star_2f         int64
star_1f       float64
fulfilled1      int64
dtype: object

In [82]:
df_train.isna().sum()

id              0
title           0
Rating          0
maincateg     526
platform        0
price1          0
actprice1       0
Offer %         0
norating1     678
noreviews1    578
star_5f       588
star_4f       539
star_3f       231
star_2f         0
star_1f         0
fulfilled1      0
dtype: int64

In [83]:
df_test.isna().sum()

id              0
title           0
Rating        203
maincateg      67
platform        0
actprice1       0
norating1       0
noreviews1      0
star_5f        68
star_4f         0
star_3f         0
star_2f         0
star_1f       186
fulfilled1      0
dtype: int64

In [84]:
import math
def fill_norating1(df):
    for ind in df.index:
        if math.isnan(df['norating1'][ind]):
            df['norating1'][ind] = df['star_1f'][ind] + df['star_2f'][ind] + df['star_3f'][ind] + df['star_4f'][ind] + df['star_5f'][ind]

In [85]:
def fill_maincateg(df):
    for ind in df.index:
        string = df['maincateg'][ind]
        if string != string:
            categ = 'Unisex'
            if "Women" in df['title'][ind]:
                categ = 'Women'
            elif "Men" in df['title'][ind]:
                categ = 'Men'
                
            df['maincateg'][ind] = categ

In [86]:
# filling the nan values in df_train
df_train.star_5f.fillna(value=0 ,inplace=True)
df_train.star_4f.fillna(value=0, inplace=True)
df_train.star_3f.fillna(value=0, inplace=True)
#df_na = df_train[df_train.maincateg.isna()]
fill_maincateg(df_train)
#df_na = df_train[df_train.norating1.isna()]
fill_norating1(df_train)
df_train.noreviews1.fillna(value=0, inplace=True)

# filling the nan values in df_test
df_test.star_5f.fillna(value=0, inplace=True)
df_test.star_1f.fillna(value=0, inplace=True)
df_test.Rating.fillna(value=df_test.Rating.mean(), inplace=True)
df_test.maincateg.fillna(value=df_train.maincateg.mode()[0], inplace=True)

C:\Users\Rohan\AppData\Local\Temp/ipykernel_12148/2550102499.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['maincateg'][ind] = categ
C:\Users\Rohan\AppData\Local\Temp/ipykernel_12148/3616019896.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['norating1'][ind] = df['star_1f'][ind] + df['star_2f'][ind] + df['star_3f'][ind] + df['star_4f'][ind] + df['star_5f'][ind]

In [87]:
print(df_train.isna().sum())
print(df_test.isna().sum())

id            0
title         0
Rating        0
maincateg     0
platform      0
price1        0
actprice1     0
Offer %       0
norating1     0
noreviews1    0
star_5f       0
star_4f       0
star_3f       0
star_2f       0
star_1f       0
fulfilled1    0
dtype: int64
id            0
title         0
Rating        0
maincateg     0
platform      0
actprice1     0
norating1     0
noreviews1    0
star_5f       0
star_4f       0
star_3f       0
star_2f       0
star_1f       0
fulfilled1    0
dtype: int64

In [88]:
df_train.maincateg.value_counts()

Women     9056
Men       6613
Unisex      61
Name: maincateg, dtype: int64

In [89]:
# converting the star count variables to int64
df_train.star_5f = df_train.star_5f.astype('int64')
df_train.star_4f = df_train.star_4f.astype('int64')
df_train.star_3f = df_train.star_3f.astype('int64')
df_train.norating1 = df_train.norating1.astype('int64')
df_train.noreviews1 = df_train.noreviews1.astype('int64')

df_test.star_5f = df_test.star_5f.astype('int64')
df_test.star_1f = df_test.star_1f.astype('int64')

print('Train :\n',df_train.dtypes,sep='')
print('\nTest :\n',df_test.dtypes,sep='')

Train :
id              int64
title          object
Rating        float64
maincateg      object
platform       object
price1          int64
actprice1       int64
Offer %        object
norating1       int64
noreviews1      int64
star_5f         int64
star_4f         int64
star_3f         int64
star_2f         int64
star_1f         int64
fulfilled1      int64
dtype: object

Test :
id              int64
title          object
Rating        float64
maincateg      object
platform       object
actprice1       int64
norating1       int64
noreviews1      int64
star_5f         int64
star_4f         int64
star_3f         int64
star_2f         int64
star_1f         int64
fulfilled1      int64
dtype: object

In [90]:
# converting the offer_% column to float
df_train['Offer %'] = df_train['Offer %'].str.replace('%','').astype('float64')

In [91]:
# selecting the non target columns
non_target_cols = [cols for cols in df_train.columns if cols not in ['price1','Offer %']]
non_target_cols

['id',
 'title',
 'Rating',
 'maincateg',
 'platform',
 'actprice1',
 'norating1',
 'noreviews1',
 'star_5f',
 'star_4f',
 'star_3f',
 'star_2f',
 'star_1f',
 'fulfilled1']

In [92]:
X = df_train[non_target_cols]
y = df_train['price1']

In [117]:
# one hot encoding the data
X_encoded = pd.get_dummies(X,columns=['maincateg','platform'])
X_encoded.drop(columns=['maincateg_Unisex'],axis=1,inplace=True)
df_test_encoded = pd.get_dummies(df_test,columns=['maincateg','platform'])

In [118]:
df_test_encoded.sample()

,id,title,Rating,actprice1,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1,maincateg_Men,maincateg_Women,platform_Amazon,platform_Flipkart
3185,3854,Sneakers for men(blue_6) Sneakers For Men (Blue),4.1,999,25516,3703,13885,5238,2906,1256,2231,1,1,0,0,1

In [119]:
# exrracting the ids for submitting
df_test_ids = df_test.id
df_test_ids = np.array(df_test_ids)

In [120]:
#dropping title and id cols
X_encoded.drop(columns=['id','title'],inplace=True, axis=1)
df_test_encoded.drop(columns=['id','title'],inplace=True, axis=1)

In [121]:
df_test_encoded.sample()

,Rating,actprice1,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1,maincateg_Men,maincateg_Women,platform_Amazon,platform_Flipkart
3530,4.5,999,10,1,6,3,1,0,0,0,0,1,0,1

In [122]:
# scaling the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
#scaler_test = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X_encoded),columns=X_encoded.columns)
df_test_scaled = pd.DataFrame(scaler.fit_transform(df_test_encoded),columns=df_test_encoded.columns)

In [123]:
df_test_scaled.head()

,Rating,actprice1,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1,maincateg_Men,maincateg_Women,platform_Amazon,platform_Flipkart
0,-0.713176,-0.29649,1.936287,1.636973,1.941215,1.222161,1.899232,2.959104,3.650607,0.808863,1.201980,-1.201980,-0.142244,0.142244
1,-0.375321,-0.68696,0.002051,-0.006015,-0.012112,0.005756,0.024895,0.045601,0.059147,0.808863,-0.831961,0.831961,-0.142244,0.142244
2,-0.375321,-0.29649,-0.197172,-0.190255,-0.199956,-0.190514,-0.174789,-0.198282,-0.211073,0.808863,-0.831961,0.831961,-0.142244,0.142244
3,-0.375321,1.26539,-0.209517,-0.196536,-0.213406,-0.196867,-0.188265,-0.224471,-0.224829,0.808863,1.201980,-1.201980,-0.142244,0.142244
4,-0.375321,-0.29649,-0.043911,-0.046841,-0.041611,-0.075494,-0.038808,-0.018234,0.046373,-1.236304,1.201980,-1.201980,-0.142244,0.142244

In [185]:
# splitting the data into train and validation
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val = train_test_split(X_scaled,y,test_size=0.15)

In [186]:
print(X_train.shape)
print(X_val.shape)

(13370, 14)
(2360, 14)

In [187]:
# importing models
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error

In [188]:
# first using the basic linear regression
lr_model = LinearRegression()
lr_model.fit(X_train,y_train)
lr_preds = lr_model.predict(X_val)
lr_mse = mean_squared_error(y_val,lr_preds)
print(lr_mse**0.5)

290.79286639907474

In [189]:
# submitting the best performing model's output
lr_model.fit(X_val,y_val)
lr_preds = lr_model.predict(X_val)
lr_mse = mean_squared_error(y_val,lr_preds)
print(lr_mse**0.5)

290.2120309087997

In [190]:
# using the random forest regressor
rf_model = RandomForestRegressor(n_estimators=500)
rf_model.fit(X_train,y_train)
rf_preds = rf_model.predict(X_val)
rf_mse = mean_squared_error(y_val,rf_preds)
print(rf_mse**0.5)

209.26522580898157

In [177]:
rf_model.fit(X_val,y_val)
rf_preds = rf_model.predict(X_val)
rf_mse = mean_squared_error(y_val,rf_preds)
print(rf_mse**0.5)

75.53635304776839

In [178]:
# using xg boost regressor
xgb_model = XGBRegressor()
xgb_model.fit(X_train,y_train)
xgb_preds = xgb_model.predict(X_val)
xgb_mse = mean_squared_error(y_val,xgb_preds)
print(xgb_mse**0.5)

308.6613352990282

In [179]:
xgb_model.fit(X_val,y_val)
xgb_preds = xgb_model.predict(X_val)
xgb_mse = mean_squared_error(y_val,xgb_preds)
print(xgb_mse**0.5)

119.03113974754528

In [180]:
# from sklearn.model_selection import RandomizedSearchCV 

# ## Hyper Parameter Optimization
# n_estimators = [100, 500, 900, 1100, 1500]
# max_depth = [2, 3, 5, 10, 15]
# booster=['gbtree','gblinear']
# learning_rate=[0.01,0.05,0.5,0.1,0.15,0.20]
# min_child_weight=[1,2,3,4]

# # Define the grid of hyperparameters to search
# hyperparameter_grid = {
#     'n_estimators': n_estimators,
#     'max_depth':max_depth,
#     'learning_rate':learning_rate,
#     'min_child_weight':min_child_weight,
#     }

# # Set up the random search with 4-fold cross validation
# random_cv = RandomizedSearchCV(estimator=xgb_model,
#             param_distributions=hyperparameter_grid,
#             cv=5, n_iter=50,
#             scoring = 'neg_mean_absolute_error',n_jobs = 4,
#             verbose = 5, 
#             return_train_score = True,
#             random_state=42)

# random_cv.fit(X_train,y_train)

# print(random_cv.best_estimator_)


# # base_score=0.5, booster='gbtree', callbacks=None,
# #              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
# #              early_stopping_rounds=None, enable_categorical=False,
# #              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
# #              importance_type=None, interaction_constraints='',
# #              learning_rate=0.1, max_bin=256, max_cat_to_onehot=4,
# #              max_delta_step=0, max_depth=10, max_leaves=0, min_child_weight=1,
# #              missing=nan, monotone_constraints='()', n_estimators=1500,
# #              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
# #              reg_alpha=0, reg_lambda=1, ...

In [181]:
# best_xgb_model = random_cv.best_estimator_
# best_xgb_model.fit(X_train,y_train)
# xgb_preds = best_xgb_model.predict(X_val)
# xgb_mse = mean_squared_error(y_val,xgb_preds)
# print("Train - ", xgb_mse**0.5)
# best_xgb_model.fit(X_val,y_val)
# xgb_preds = best_xgb_model.predict(X_val)
# xgb_mse = mean_squared_error(y_val,xgb_preds)
# print("Test - ", xgb_mse**0.5)

In [191]:
# submitting the best performing model's output
preds_final =  rf_model.predict(df_test_scaled)

In [192]:
final_sub = pd.DataFrame({'id':df_test_ids,'price1':preds_final},columns=['id','price1'])
final_sub.set_index('id',inplace=True)
final_sub

           price1
id
2242   363.754550
20532  319.790400
10648  403.971800
20677  857.218000
12593  390.714568
...           ...
14033  436.568071
297    487.124254
18733  380.156800
6162   250.986000
13574  695.465333

[5244 rows x 1 columns]

In [193]:
final_sub.to_csv('submission.csv')